apiVersion: v1
kind: Service
metadata:
  name: vod-management-service
spec:
  selector:
    app: vod-management-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000 
  type: ClusterIP  # Belso kommunikációhoz