apiVersion: v1
kind: Service
metadata:
  name: vod-frontend
spec:
  selector:
    app: vod-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
  type: NodePort
