apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1  # Ha szükséges, több példány is futhat
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: bankilacko11/user-service:latest 
          ports:
            - containerPort: 5000  
          env:
            - name: DATABASE_URL
              value: "postgres://user:password@database-service:5432/vod-database"