apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-monitor
  namespace: default
  labels:
    app: analytics-service
    release: prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
    - port: http
      path: /internal/metrics
      interval: 30s

