apiVersion: apps/v1
kind: Deployment
metadata:
  name: transcoding-service
  labels:
    app: transcoding-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transcoding-service
  template:
    metadata:
      labels:
        app: transcoding-service
    spec:
      containers:
      - name: transcoding-service
        image: bankilacko11/transcoding-service:latest
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: vod-storage
          mountPath: /vod 
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: vod-storage
        persistentVolumeClaim:
          claimName: vod-storage-claim      
