apiVersion: v1
kind: Service
metadata:
  name: nginx-vod-service
spec:
  selector:
    app: nginx-vod
  ports:
    - name: http
      protocol: TCP
      port: 7000
      targetPort: 7000
      nodePort: 30070
  type: NodePort